# Generated by Django 3.1.4 on 2020-12-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndts', '0002_ndt_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ndt',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choose',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
