# Generated by Django 3.1.4 on 2020-12-13 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('ndts', '0002_remove_ndt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
            preserve_default=False,
        ),
    ]
