# Generated by Django 3.1.4 on 2020-12-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndts', '0003_auto_20201219_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndt',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
