# Generated by Django 3.1.4 on 2020-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndts', '0005_ndt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndt',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
